/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package valkyrie.enigma.enigmaplus;

/**
 *
 * @author heshanjayasinghe
 */
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import valkyrie.enigma.enigmaplus.Controller.AutoSuggestor;
import valkyrie.enigma.enigmaplus.view.Login;
import valkyrie.enigma.enigmaplus.view.Profile_view;
import valkyrie.enigma.enigmaplus.view.Questionmain;

public class EnigmaMain extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public EnigmaMain() {
        initComponents();
        loadlogin();
        head_main.setVisible(false);
        panelnotification.setVisible(false);
        panelsignout.setVisible(false);
        
//        AutoSuggestor autoSuggestor = new AutoSuggestor(Questionmain.txt_mainsearch, null, null, Color.WHITE.brighter(), Color.BLUE, Color.RED, 0.100f) {
//        @Override
//            public boolean wordTyped(String typedWord) {
//            System.out.println("ok wada");
//                ArrayList<String> words = new ArrayList<>();
//                words.add("hello");
//                words.add("heritage");
//                words.add("happiness");
//                words.add("goodbye");
//                words.add("cruel");
//                words.add("car");
//                words.add("war");
//                words.add("will");
//                words.add("world");
//                words.add("wall");
//
//
//                setDictionary(words);
//
//                return super.wordTyped(typedWord);
//            }
//        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelnotification = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        panelsignout = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        profile_pic_signout = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        head_signup = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        head_main = new javax.swing.JPanel();
        head_main_userName = new javax.swing.JButton();
        mini_profile_pic = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton27.setBackground(new java.awt.Color(255, 255, 255));
        jButton27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton27.setBorderPainted(false);

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel52.setText("Answer : ");

        jLabel53.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel53.setText("12.00 pm");

        jLabel54.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel54.setText("how to create java class");

        jLabel55.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel55.setText("open java project  and  type classs name {} ...");

        jButton28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton28.setBorderPainted(false);

        jButton29.setBackground(new java.awt.Color(255, 255, 255));
        jButton29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton29.setBorderPainted(false);

        jButton30.setBackground(new java.awt.Color(255, 255, 255));
        jButton30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton30.setBorderPainted(false);

        jLabel56.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel56.setText("Answer : ");

        jLabel57.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel57.setText("12.00 pm");

        jLabel58.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel58.setText("how to create java class");

        jLabel59.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel59.setText("open java project  and  type classs name {} ...");

        jLabel60.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel60.setText("Answer : ");

        jLabel61.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel61.setText("12.00 pm");

        jLabel62.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel62.setText("how to create java class");

        jLabel63.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel63.setText("open java project  and  type classs name {} ...");

        jLabel64.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel64.setText("Answer : ");

        jLabel65.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel65.setText("12.00 pm");

        jLabel66.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel66.setText("how to create java class");

        jLabel67.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel67.setText("open java project  and  type classs name {} ...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel53))
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel55))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel58))
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel56))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel57))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel60))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel61))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel63))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel62))
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel66)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel65))
                            .addComponent(jLabel64)
                            .addComponent(jLabel67))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel53))
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel55))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel54)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel58))
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel56))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel57)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel60))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel61))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel63))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel62))
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel66))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel65))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel64))
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel67))))
        );

        jButton23.setBackground(new java.awt.Color(153, 153, 153));
        jButton23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton23.setText("See all");
        jButton23.setBorderPainted(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelnotificationLayout = new javax.swing.GroupLayout(panelnotification);
        panelnotification.setLayout(panelnotificationLayout);
        panelnotificationLayout.setHorizontalGroup(
            panelnotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnotificationLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelnotificationLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelnotificationLayout.setVerticalGroup(
            panelnotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnotificationLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelsignout.setBackground(new java.awt.Color(255, 255, 255));
        panelsignout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelsignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelsignoutMouseExited(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(255, 255, 255));
        jButton24.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton24.setText("Profile");
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton24MouseEntered(evt);
            }
        });
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton25.setText("Sign out");
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton25MouseEntered(evt);
            }
        });
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        profile_pic_signout.setBackground(new java.awt.Color(255, 255, 255));
        profile_pic_signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valkyrie/enigma/enigmaplus/view/images/malithi50.png"))); // NOI18N

        javax.swing.GroupLayout panelsignoutLayout = new javax.swing.GroupLayout(panelsignout);
        panelsignout.setLayout(panelsignoutLayout);
        panelsignoutLayout.setHorizontalGroup(
            panelsignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsignoutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(profile_pic_signout)
                .addGap(18, 18, 18)
                .addGroup(panelsignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelsignoutLayout.setVerticalGroup(
            panelsignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsignoutLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelsignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_pic_signout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelsignoutLayout.createSequentialGroup()
                        .addComponent(jButton24)
                        .addGap(12, 12, 12)
                        .addComponent(jButton25)))
                .addGap(9, 9, 9))
        );

        jDesktopPane1.setLayout(null);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );

        head_signup.setBackground(new java.awt.Color(135, 27, 133));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sign in");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enigma+");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valkyrie/enigma/enigmaplus/view/images/IFS.jpg"))); // NOI18N

        javax.swing.GroupLayout head_signupLayout = new javax.swing.GroupLayout(head_signup);
        head_signup.setLayout(head_signupLayout);
        head_signupLayout.setHorizontalGroup(
            head_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_signupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(54, 54, 54))
        );
        head_signupLayout.setVerticalGroup(
            head_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_signupLayout.createSequentialGroup()
                .addGroup(head_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(head_signupLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(head_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        head_main.setBackground(new java.awt.Color(147, 29, 145));

        head_main_userName.setBackground(new java.awt.Color(255, 255, 255));
        head_main_userName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        head_main_userName.setForeground(new java.awt.Color(255, 255, 255));
        head_main_userName.setText("Malithi Gunathilaka");
        head_main_userName.setBorder(null);
        head_main_userName.setBorderPainted(false);
        head_main_userName.setContentAreaFilled(false);
        head_main_userName.setFocusPainted(false);
        head_main_userName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        head_main_userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                head_main_userNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                head_main_userNameMouseExited(evt);
            }
        });
        head_main_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                head_main_userNameActionPerformed(evt);
            }
        });

        mini_profile_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valkyrie/enigma/enigmaplus/view/images/malithi.jpg"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valkyrie/enigma/enigmaplus/view/images/notification_2.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Enigma+");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valkyrie/enigma/enigmaplus/view/images/IFS.jpg"))); // NOI18N

        javax.swing.GroupLayout head_mainLayout = new javax.swing.GroupLayout(head_main);
        head_main.setLayout(head_mainLayout);
        head_mainLayout.setHorizontalGroup(
            head_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_mainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mini_profile_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(head_main_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        head_mainLayout.setVerticalGroup(
            head_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_mainLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(head_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(head_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mini_profile_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, head_mainLayout.createSequentialGroup()
                .addComponent(head_main_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(head_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head_main, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(head_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(810, 810, 810)
                        .addComponent(panelnotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(830, 830, 830)
                        .addComponent(panelsignout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelnotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelsignout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void head_main_userNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_head_main_userNameMouseEntered
       panelsignout.setVisible(true);
        
    }//GEN-LAST:event_head_main_userNameMouseEntered

    private void head_main_userNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_head_main_userNameMouseExited
        //panelsignout.setVisible(false);
    }//GEN-LAST:event_head_main_userNameMouseExited

    private void head_main_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_head_main_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_head_main_userNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (panelnotification.isVisible() == false) {
            panelnotification.setVisible(true);
        } else {
            panelnotification.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JInternalFrame intr = new Questionmain();
        jDesktopPane1.add(intr);
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(EnigmaMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        intr.show();
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException e) {
            System.out.println(e);
        }
//        panelquestionmain.setVisible(true);
//        panelask.setVisible(false);
//        panelaskview.setVisible(false);
//        panelnotification.setVisible(false);
//        panelsignout.setVisible(false);
//        panelnotification.setVisible(false);
//        panelsignup.setVisible(false);
//        panelquestionview.setVisible(false);
//        panelProfile_view.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseEntered
        panelsignout.setVisible(true);
    }//GEN-LAST:event_jButton24MouseEntered

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        JInternalFrame intr = new Profile_view();
        jDesktopPane1.add(intr);
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(EnigmaMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        intr.show();
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException e) {
            this.setVisible(false);
        }
//        panelProfile_view.setVisible(true);
//        panelquestionmain.setVisible(false);
//        int userID = this.userID;
//        try {
//            User u = UserController.profileView(userID);
//            panelProfile_view_name.setText(u.getFname() + " " + u.getLname());
//            panelProfile_view_email.setText(u.getEmail());
//            panelProfile_view_designation.setText(u.getProfession());
//            panelProfile_view_reputation.setText(Integer.toString(u.getReputation()));
//            panelProfile_view_expertise.setText(u.getExpertis());
//        } catch (ClassNotFoundException ex) {
//            //System.out.println("in here");
//            ex.printStackTrace();
//        } catch (SQLException ex) {
//            //System.out.println("or in here");
//            ex.printStackTrace();
//        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseEntered
        panelsignout.setVisible(true);
    }//GEN-LAST:event_jButton25MouseEntered

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        JInternalFrame intr = new Login();
        jDesktopPane1.add(intr);
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(EnigmaMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        intr.show();
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException e) {
            this.setVisible(false);
        }
          head_main.setVisible(false);
          head_signup.setVisible(true);
          panelsignout.setVisible(false);
//        panellogin.setVisible(true);
//        panelquestionmain.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void panelsignoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsignoutMouseExited
        panelsignout.setVisible(false);
    }//GEN-LAST:event_panelsignoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnigmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnigmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnigmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnigmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnigmaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel head_main;
    public static javax.swing.JButton head_main_userName;
    public static javax.swing.JPanel head_signup;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton8;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainpanel;
    public static javax.swing.JLabel mini_profile_pic;
    private javax.swing.JPanel panelnotification;
    private javax.swing.JPanel panelsignout;
    public static javax.swing.JLabel profile_pic_signout;
    // End of variables declaration//GEN-END:variables

    private void loadlogin() {
        JInternalFrame intr = new Login();
        jDesktopPane1.add(intr);
        intr.show();
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException e) {
            
        }
    }
}
