package valkyrie.enigma.enigmaplus.view;

import com.hp.hpl.jena.query.Query;
import com.hp.hpl.jena.query.QueryExecution;
import com.hp.hpl.jena.query.QueryExecutionFactory;
import com.hp.hpl.jena.query.QueryFactory;
import com.hp.hpl.jena.query.QuerySolution;
import com.hp.hpl.jena.query.ResultSet;
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.util.FileManager;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import valkyrie.enigma.enigmaplus.Controller.QuestionController;
import static valkyrie.enigma.enigmaplus.EnigmaMain.jDesktopPane1;



public class ask extends javax.swing.JInternalFrame {
String title1;
String short_des;
String des;
    /**
     * Creates new form ask
     */
    public ask() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelask = new javax.swing.JPanel();
        panelask_txt_title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelask_txt_dis = new javax.swing.JTextArea();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelask_txt_sdes = new javax.swing.JTextArea();
        txt_tags = new javax.swing.JTextField();
        tagpanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);

        panelask.setBackground(new java.awt.Color(255, 255, 255));

        panelask_txt_title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelask_txt_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelask_txt_titleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Title");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Short-Description");

        panelask_txt_dis.setColumns(20);
        panelask_txt_dis.setRows(5);
        jScrollPane2.setViewportView(panelask_txt_dis);

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButton2.setText("Add code");

        jToggleButton3.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButton3.setText("Attach file");

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButton1.setText("Attach image");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Description");

        panelask_txt_sdes.setColumns(20);
        panelask_txt_sdes.setRows(5);
        jScrollPane4.setViewportView(panelask_txt_sdes);

        javax.swing.GroupLayout tagpanelLayout = new javax.swing.GroupLayout(tagpanel);
        tagpanel.setLayout(tagpanelLayout);
        tagpanelLayout.setHorizontalGroup(
            tagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tagpanelLayout.setVerticalGroup(
            tagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jLabel19.setText("Add tags :");

        javax.swing.GroupLayout panelaskLayout = new javax.swing.GroupLayout(panelask);
        panelask.setLayout(panelaskLayout);
        panelaskLayout.setHorizontalGroup(
            panelaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaskLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelaskLayout.createSequentialGroup()
                        .addGroup(panelaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelask_txt_title)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelaskLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelaskLayout.createSequentialGroup()
                        .addGroup(panelaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tagpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelaskLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(63, 63, 63)
                                .addComponent(txt_tags, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))
                    .addGroup(panelaskLayout.createSequentialGroup()
                        .addGroup(panelaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 928, Short.MAX_VALUE))))
        );
        panelaskLayout.setVerticalGroup(
            panelaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(panelask_txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton1)
                    .addComponent(txt_tags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelask_txt_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelask_txt_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelask_txt_titleActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        askview intr = new askview(this);
        jDesktopPane1.add(intr);
        intr.show();
        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException e) {

        }

        //save values which is in text filed and pass those values in to askview panel and save it at the end of the save button in askview panel
        //load best profestionals to table in askview 
//        askview av = new  askview(intr);
//        DefaultTableModel tmodel = (DefaultTableModel) av.jTable1.getModel();
//                Object[] row1 = {"01","hell","no"};
//                tmodel.addRow(row1);
        // System.out.println(fname+" "+lname+","+des+","+rep);
     //   FileManager.get().addLocatorClassLoader(Jena_Enigma.class.getClassLoader());

        Model model = FileManager.get().loadModel("/Users/heshanjayasinghe/Documents/A-enigmaProject/26_3_2015/EnigmaSuperClient/EnigmaSuperClient/src/valkyrie/enigma/enigmaplus/jena_enigma/enigmardf2.rdf");
        String queryString = "PREFIX sep: <http://www.semanticweb.org/hesh/ontologies/valkyrie/enigmaplus/ontology#>"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>"
                + "PREFIX strg: <http://www.w3.org/2001/XMLSchema#string#>"
                + "SELECT  * "
                + "WHERE {"
                + "?User sep:lname ?lname ."
                + "?User sep:designation ?des ."
                + "?User sep:fname ?fname ."
                + "?User sep:reputation ?rep"
                + "}";
        Query query = QueryFactory.create(queryString);

        QueryExecution qexec = QueryExecutionFactory.create(query, model);

        try {
            ResultSet results = qexec.execSelect();
            while (results.hasNext()) {
                QuerySolution soln = results.nextSolution();
                String fname = soln.getLiteral("fname").getLexicalForm();
                String lname = soln.getLiteral("lname").getLexicalForm();
                String des = soln.getLiteral("des").getLexicalForm();
                String rep = soln.getLiteral("rep").getLexicalForm();

                intr.setTable(fname, lname, des, rep);
                System.out.println(fname + " " + lname + "," + des + "," + rep);
            }
        } finally {
            qexec.close();
        }
        QuestionController qc = new QuestionController();
        title1 = panelask_txt_title.getText();
        short_des = panelask_txt_sdes.getText();
        des = panelask_txt_dis.getText();
        
        intr.setValues(title1, short_des, des, qc.qidCounter());
        
        
         //String ctgry = (String) q_category.getSelectedItem();
         
//        panelask.setVisible(false);
//        panelaskview.setVisible(true);
//
    /*    title = panelask_txt_title.getText();
         short_des = panelask_txt_sdes.getText();
         des = panelask_txt_dis.getText();
         ctgry = (String) q_category.getSelectedItem();

         try {
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         Connection conn = DBConnection.getDBConnection().getConnection();
         if (ctgry != "All") {
         PreparedStatement stat = conn.prepareStatement("SELECT uid,fname,lname,profession,reputation FROM user WHERE expertis=? ORDER BY reputation DESC;");
         stat.setString(1, (String) q_category.getSelectedItem());

         ResultSet rslt = stat.executeQuery();

         for (int i = 0; i <= 5; i++) {
         rslt.next();
         String name = rslt.getString("fname") + " " + rslt.getString("lname");
         String designation = rslt.getString("profession");
         String reputation = rslt.getString("reputation");
         Object[] row = {name, designation, reputation};

         model.addRow(row);
         }

         } else {
         PreparedStatement stat = conn.prepareStatement("SELECT uid,fname,lname,profession,reputation FROM user ORDER BY reputation DESC;");
         ResultSet rslt = stat.executeQuery();

         for (int i = 0; i <= 5; i++) {
         rslt.next();
         String name = rslt.getString("fname") + " " + rslt.getString("lname");
         String designation = rslt.getString("profession");
         String reputation = rslt.getString("reputation");
         Object[] row = {name, designation, reputation};

         model.addRow(row);
         }

         }
         } catch (ClassNotFoundException | SQLException ex) {
         System.out.println(ex);
         }*/
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPanel panelask;
    private javax.swing.JTextArea panelask_txt_dis;
    private javax.swing.JTextArea panelask_txt_sdes;
    private javax.swing.JTextField panelask_txt_title;
    public static javax.swing.JPanel tagpanel;
    private javax.swing.JTextField txt_tags;
    // End of variables declaration//GEN-END:variables
}
