/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package valkyrie.enigma.enigmaplus.view;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import valkyrie.enigma.enigmaplus.Controller.UserController;
import static valkyrie.enigma.enigmaplus.EnigmaMain.jDesktopPane1;


/**
 *
 * @author avinda
 */
public class editProfile extends javax.swing.JInternalFrame {

    /**
     * Creates new form editProfile
     */
    public editProfile() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.initialize();
    }
    
    public void initialize(){
        
        UserController uc = new UserController();
        uc.getUser(uc.getUserLogged());
        panelProfile_view_name.setText(uc.u1.getFname()+" "+uc.u1.getLname());
        panelProfile_view_email.setText(uc.u1.getEmail());
        panelProfile_view_designation.setText(uc.u1.getProfession());
        panelProfile_view_Expertise.setText(uc.u1.getInterrested());
        Image_path.setText(uc.u1.getPic());
      
        
        //"C:\\Users\\avinda\\Desktop\\ishara\\project_files\\EnigmaSuperClient\\EnigmaSuperClient\\src\\valkyrie\\enigma\\enigmaplus\\view\\images\\profile pic_3.jpg"
       // "C:\\Users\\avinda\\Desktop\\ishara\\project_files\\EnigmaSuperClient\\EnigmaSuperClient\\Images\\IMG_0619.JPG"
        //"C:\\Users\\avinda\\Desktop\\ishara\\project_files\\EnigmaSuperClient\\EnigmaSuperClient\\Images\\2014-09-27-2482.jpg"
        //"D:\\ISHARA\\Images\\wso2_hackathon\\fb\\2014-09-27-2482.jpg"
        //C:\\Users\\avinda\\Desktop\\ishara\\project_files\\EnigmaSuperClient\\EnigmaSuperClient\\src\\valkyrie\\enigma\\enigmaplus\\view\\profile_pic.jpg

       // ImageIcon icon = new ImageIcon("C:\\Users\\avinda\\Desktop\\ishara\\project_files\\EnigmaSuperClient\\EnigmaSuperClient\\src\\valkyrie\\enigma\\enigmaplus\\view\\profile_pic.jpg");
        //ImageIcon ic = new ImageIcon("C:\\Users\\avinda\\Desktop\\ishara\\project_files\\EnigmaSuperClient\\EnigmaSuperClient\\src\\valkyrie\\enigma\\enigmaplus\\view\\profile_pic.jpg");
        BufferedImage image;
        try {
            image = ImageIO.read(new File(uc.u1.getPic()));
            BufferedImage resizedImage = resize(image, 320, 302);//resize the image to 100x100
            ImageIcon icon = new ImageIcon(resizedImage);
            profile_pic.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(editProfile.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public static BufferedImage resize(BufferedImage image, int width, int height) {
    BufferedImage BI = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
    Graphics2D g2d = (Graphics2D) BI.createGraphics();
    g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
    g2d.drawImage(image, 0, 0, width, height, null);
    g2d.dispose();
    return BI;
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        profile_Expertise = new javax.swing.JLabel();
        profile_name = new javax.swing.JLabel();
        profile_email = new javax.swing.JLabel();
        panelProfile_view_name = new javax.swing.JTextField();
        panelProfile_view_email = new javax.swing.JTextField();
        profile_designation = new javax.swing.JLabel();
        panelProfile_view_designation = new javax.swing.JTextField();
        panelProfile_view_Expertise = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        profile_pic = new javax.swing.JLabel();
        Image_path = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        profile_Expertise.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        profile_Expertise.setText("Interested");

        profile_name.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        profile_name.setText("Name ");

        profile_email.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        profile_email.setText("Email");

        panelProfile_view_name.setText("Malithi Gunathilaka");

        panelProfile_view_email.setText("email@domain.com");
        panelProfile_view_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelProfile_view_emailActionPerformed(evt);
            }
        });

        profile_designation.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        profile_designation.setText("Designation");

        panelProfile_view_designation.setText("Student");
        panelProfile_view_designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelProfile_view_designationActionPerformed(evt);
            }
        });

        panelProfile_view_Expertise.setText("Java, C#");
        panelProfile_view_Expertise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelProfile_view_ExpertiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_email)
                    .addComponent(profile_Expertise)
                    .addComponent(profile_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProfile_view_email, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProfile_view_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProfile_view_Expertise, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProfile_view_name, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_name)
                    .addComponent(panelProfile_view_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelProfile_view_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_email))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_designation)
                    .addComponent(panelProfile_view_designation, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelProfile_view_Expertise, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_Expertise))
                .addGap(27, 27, 27))
        );

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        profile_pic.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        profile_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valkyrie/enigma/enigmaplus/view/images/profile pic_3.jpg"))); // NOI18N

        Image_path.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Image_path.setText("Path of Your image");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(profile_pic)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Image_path, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile_pic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Image_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(78, 78, 78)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelProfile_view_designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelProfile_view_designationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelProfile_view_designationActionPerformed

    private void panelProfile_view_ExpertiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelProfile_view_ExpertiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelProfile_view_ExpertiseActionPerformed

    private void panelProfile_view_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelProfile_view_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelProfile_view_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);        
        
        Profile_view intr = new Profile_view();
        jDesktopPane1.add(intr);
        intr.show();

        try {
            intr.setMaximum(true);
        } catch (PropertyVetoException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String full_name = panelProfile_view_name.getText();
        String[] name = full_name.split("\\s+");
        
        UserController uc = new UserController();
        uc.editUser(uc.getUserLogged(), name[0], name[1], panelProfile_view_email.getText(), panelProfile_view_Expertise.getText(), panelProfile_view_designation.getText(), Image_path.getText());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Image_path;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField panelProfile_view_Expertise;
    private javax.swing.JTextField panelProfile_view_designation;
    private javax.swing.JTextField panelProfile_view_email;
    private javax.swing.JTextField panelProfile_view_name;
    private javax.swing.JLabel profile_Expertise;
    private javax.swing.JLabel profile_designation;
    private javax.swing.JLabel profile_email;
    private javax.swing.JLabel profile_name;
    private javax.swing.JLabel profile_pic;
    // End of variables declaration//GEN-END:variables
}
